language: node_js
node_js:
- '0.10'
cache:
  directories:
  - node_modules
git:
  depth: 3
sudo: false
before_deploy: grunt build
deploy:
  provider: releases
  api_key:
    secure: DYuK8aAG5fH6jH3tCsKHTPSLTI2vW8AD5g7Pu5ovvbynb2pf8hjQ17IZwPf8R8mKfFn93JUxL57wz4neUM8CIaZtBJW15urzXcfZxfGx7BV7fIhsE8ZwMrZM5X8mqtXFWg+Dd7GkecnE2GjtUVeql5sCMGzZDbKVWwfPZzia07zUyQVOneWZ8GRUdmSpKH0neDiqf4+32M2srC2TiJ7ZRHG2fxJkZ7mvqc1Ts1Js8FVg2emWE/fRc4e8NiiX1FOqV0Vc3XgnJD90ugIM0BwCdcyNKvwi2hKypCdMK5QRWyhljYx142Te3VHNP7kdGYxM7BNA1JQqwzC7HVOHZXiMJX0IXpYcwxELjgtp6A9WwlCCZALoI92Jk8F++y2TQ/EyILQin1fmBBHq31dsTcLBVW38idwp5dKvExoyal/0mIkKG39UmXHr+JIf/TKIhT8sIK7xQ8V0J+AYz0XR/565JS7ylldeJxaC7cKkMTjYdEAXq1lYmP3iZyUfcSppQsKaoArfk4ojBF351ElNDB8KIDZa9wL1gVQcH99zG4451jweF6hlpvA1gaR6h9WZcp3QIRkQml3uBCqAlIC5+v0iYYDLfwQslta5GucfeCwQUGQuA7hF5M5nVrjt8l/bJq1i0q3rdtX4wOrqvQii0nqYX3Y3euydsX+l4bJ7SB9Kvbg=
  file: dist/index.html
  skip_cleanup: true
  on:
    repo: PromenadeSoftware/ParlayUI
    tags: true
after_deploy: grunt travis_doc_deploy
